# Generated by Django 4.2.7 on 2023-11-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destynacja',
            fields=[
                ('id_destynacja', models.AutoField(primary_key=True, serialize=False)),
                ('adres', models.TextField()),
                ('wspolrzedne', models.CharField(max_length=19)),
                ('telefon', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Kierowca',
            fields=[
                ('id_kierowca', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField()),
                ('nazwisko', models.CharField()),
                ('pesel', models.CharField(max_length=11)),
                ('telefon', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ladunek',
            fields=[
                ('id_ladunek', models.AutoField(primary_key=True, serialize=False)),
                ('masa', models.CharField(max_length=5)),
                ('pojazd', models.CharField()),
                ('stan', models.CharField(choices=[('N', 'Nowy'), ('U', 'Uzywany')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Poczatek',
            fields=[
                ('id_poczatek', models.AutoField(primary_key=True, serialize=False)),
                ('adres', models.TextField()),
                ('wspolrzedne', models.CharField(max_length=19)),
                ('telefon', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Zleceniodawca',
            fields=[
                ('id_zleceniodawca', models.AutoField(primary_key=True, serialize=False)),
                ('telefon', models.CharField(max_length=12)),
                ('nip', models.CharField(max_length=10)),
                ('regon', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Trasy',
            fields=[
                ('id_trasa', models.AutoField(primary_key=True, serialize=False)),
                ('przychod', models.IntegerField()),
                ('wyjazd', models.CharField(max_length=8)),
                ('przyjazd', models.CharField(max_length=8)),
                ('id_kierowca', models.ForeignKey(on_delete=models.SET(''), to='Bazy.kierowca')),
                ('id_ladunek', models.ForeignKey(on_delete=models.SET(''), to='Bazy.ladunek')),
                ('id_poczatek', models.ForeignKey(on_delete=models.SET(''), to='Bazy.poczatek')),
                ('id_zleceniodawca', models.ForeignKey(on_delete=models.SET(''), to='Bazy.zleceniodawca')),
            ],
        ),
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id_pojazd', models.AutoField(primary_key=True, serialize=False)),
                ('marka', models.CharField()),
                ('ubezpieczenie', models.CharField(max_length=10)),
                ('przeglad', models.CharField(max_length=10)),
                ('nr_rejestracyjny', models.CharField(max_length=8)),
                ('id_kierowca', models.ForeignKey(on_delete=models.SET(''), to='Bazy.kierowca')),
            ],
        ),
        migrations.AddField(
            model_name='kierowca',
            name='id_pojazd',
            field=models.ForeignKey(on_delete=models.SET(''), to='Bazy.pojazd'),
        ),
    ]
