# Generated by Django 5.0.1 on 2024-01-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bazy', '0002_remove_kierowca_id_pojazd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladunek',
            name='stan',
            field=models.CharField(choices=[('N', 'Nowy'), ('U', 'Używany')], max_length=1),
        ),
    ]
