# Generated by Django 5.0.1 on 2024-01-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bazy', '0003_alter_ladunek_stan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trasy',
            name='przyjazd',
        ),
        migrations.RemoveField(
            model_name='trasy',
            name='wyjazd',
        ),
        migrations.AddField(
            model_name='trasy',
            name='data',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
