# Generated by Django 5.0.1 on 2024-01-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bazy', '0004_remove_trasy_przyjazd_remove_trasy_wyjazd_trasy_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trasy',
            name='data',
        ),
    ]
